use customer_behavior;
select * from customer limit 20;
-- What is the total revenue generated by male vs female customer?
select gender,sum(purchase_amount) as revenue from customer
group by gender;
-- Which customer used a discount but still spend more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied='Yes' AND
 purchase_amount>(select avg(purchase_amount) from customer);
 -- Which are the top 5 product with the highest average review rating ?
 select item_purchased,round(avg(review_rating),2)as average_rating from customer
 group by item_purchased
 order by average_rating desc
 limit 5;
 -- Compare the average purchase amount between standard and express shipping ?
 select shipping_type,round(avg(purchase_amount),2) as average_amount from customer
 where shipping_type IN('Standard','Express')
 group by shipping_type;
 -- Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
 select subscription_status, 
 count(customer_id) as customer_count,round(avg(purchase_amount),2) as average_spend,
 sum(purchase_amount)as total_revenue
 from customer
 group by subscription_status;
 -- which 5 product have the highest percentage of purchase with discounts applied?
select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)*100.0/count(*),2) as discount_rate from customer
group by item_purchased
order by discount_rate desc limit 5;
-- Segment customers into New,Returning,Loyal based on their total number of previous purchase, and show the count of each segment
With customer_type as (select
customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
 else 'Loyal'
end as customer_segment from customer)
select customer_segment,
count(*) as number_of_customers from customer_type
group by customer_segment;
-- What are the top 3 most purchased product within each category?
With order_count as (select item_purchased,category,
count(customer_id) as item_count ,
row_number () over (partition by category order by count(customer_id) desc)  as row_num from customer
group by category,item_purchased)
select row_num,category,item_purchased from order_count
where row_num <= 3;
-- Are customers who are repeat buyers(more than 5 previous purchase)also likly to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers from customer 
where previous_purchases >= 5
group by  subscription_status;
-- What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as revenue from customer
group by age_group order by revenue desc;

